### ISSUE TITLE
Enhancement Suggestion: Add a Gitter Chat room for PSGitHub Repo

### ISSUE THREAD

**Issue by PlagueHO** [pcgeek86/PSGitHub#12]
I have a few other enhancement suggestions (unit tests, integrate with AppVeyor CI to automate test/release process to PSGallery), and I'm also keen to help out with code PR's once I've got a bit more free time in a week or two.

But I thought rather than submitting Issue's for all the enhancement suggestions it might be easier to run them by you to see if they're inline with what you're wanting to do.

So can I suggest linking up a Gitter IM chatroom (https://gitter.im/) for this repo?

Really good video on Channel 9 BTW :+1:

**Comment by pcgeek86** [comment]
@PlagueHO Thanks for the compliment on the video, sir! Gitter is a great idea, and feel free to hit me up on Skype, too. My username is the same. :smile:

**Comment by PlagueHO** [comment]
Cool! :+1:
