### ISSUE TITLE
Update token to support per user functionallity

### ISSUE THREAD

**Issue by dotps1** [pcgeek86/PSGitHub#14]
Before submitting your issue for the PSGitHub project, please take a moment to provide the following details:
- [5.0 ] Verison of PowerShell you're using
- [ISE/ConsoleHoste ] PowerShell host you're using (eg. Console Host, ISE, Visual Studio)
- [10 Pro x64 ] Operating system you're running
- [latest ] Version of PSGitHub you're using (use `Get-Module -Name PSGitHub`)

Thanks for contributing your feedback and support! You can optionally submit a Pull Request against this project, if you have a fix you'd like to share.

I think we should update the Set-GitHubToken cmdlet to be targeted at the user.  And ideally not stored in the $PSModuleRoot path.  We could also append the username to the token file  IE: $env:USERNAME.GitHub.Token or something.

**Comment by pcgeek86** [comment]
@dotps1 Thanks Thomas -- can you help me understand what you mean by "targeted at the user?" I agree with you about not storing it in the module path. That was just an initial implementation that could probably be improved upon.

**Comment by dotps1** [comment]
i was tired when i created this, but i think in my head i was thinking if you have a pc that is used by more then one user, each user would have to keep re creating there auth token.  If we did something like bind it to the user name of the PC that would help avoid that.

**Comment by pcgeek86** [comment]
Oh, then yeah, that sounds good. As discussed on Skype, we should probably move to use `$env:AppData` and create a PSGitHub subfolder. Thanks Thomas
