### ISSUE TITLE
publish to psgallery

### ISSUE THREAD

**Issue by czhang03** [pcgeek86/PSGitHub#27]
That one is really outdated.

I have a module that depends on your module, so I really need you to do that (luckily there is nobody using my module besides me... That is also sad...)

**Comment by pcgeek86** [comment]
@chantisnake Sorry, I just saw this now. I'll take care of that today.

**Comment by ghost** [comment]
@pcgeek86 Still 2016 on PSGallery?

**Comment by pcgeek86** [comment]
Yeah sorry, I tried to use it again and ran into some bugs that I need to work out. Can't guarantee any effort on it in the short term. Care to throw in some effort and add yourself as a maintainer? I'm sure I'll pick this up again at some point. Right now I'm a little overburdened. Feel free to reach out over e-mail to discuss further.

**Comment by felixfbecker** [comment]
Just tried to install it from psgallery, but it seems super outdated

```
> Get-Module PSGitHub                                                                                                                                                    

ModuleType Version    Name                                ExportedCommands                                                                                              
---------- -------    ----                                ----------------                                                                                              
Script     0.13.9     PSGitHub                            {Get-GitHubAuthenticatedUser, Get-GitHubGist, Get-GitHubMilestone, New-GitHubGist...}                         
```
Would love to see the latest version

**Comment by pcgeek86** [comment]
@felixfbecker Sorry about that, I'll set aside some time to update the module this evening.

**Comment by johlju** [comment]
The build step has the wrong API key, so it can't publish. Not sure if that's the only problem. Not sure it's a good idea having the key public either. 

https://ci.appveyor.com/project/pcgeek86/psgithub/build/0.14.59#L198

**Comment by pcgeek86** [comment]
It's been resolved -- the API key is encrypted by AppVeyor, so no worries there.
