### ISSUE TITLE
Add Support for Github Enterprise Administration

### ISSUE THREAD

**Issue by michaelsainz** [pcgeek86/PSGitHub#48]
Hi all! I wanted to introduce myself to people here and announce my support for this project. I'm Michael Sainz, you can find out more about me [here](https://about.me/michaelsainz)!

I am going to be opening up some PR's soon with some new functionality around interacting with our on-premise solution - Github Enterprise. You can read more about it [here](https://github.com/pricing/enterprise).

Here are some of my thoughts -

- [ ] Adding support for creation of Organizations
- [ ] User Administration
- [ ] Team Administration
- [ ] Repository Migrations

I would be most thankful for reviews and critiques of this code to ensure it maintains the high standard of this project and the PowerShell community as a whole.

**Comment by felixfbecker** [comment]
Support for Enterprise landed in v0.15.192 :)
