### ISSUE TITLE
The term 'Get-AutomationPSCredential' is not recognized

### ISSUE THREAD

**Issue by eloekset** [pcgeek86/PSGitHub#5]
...as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

How to install the missing function? I find it mentioned in the Azure Automation documentation https://azure.microsoft.com/nb-no/documentation/articles/automation-credentials/#using-a-powershell-credential but I've already got the Azure module installed. For instance Get-AzureAutomationCredential is recognized in the same PowerShell session.
![2016-03-19_23-24-06](https://cloud.githubusercontent.com/assets/791721/13901610/c8ae9580-ee29-11e5-9fc4-dfb15599902f.png)

**Comment by pcgeek86** [comment]
Hey thanks for pointing this out. That's my fault for not testing it better.  This command actually comes from the Microsoft Azure Automation ISE add-on. This add-on for the PowerShell ISE helps author Microsoft Azure Automation Runbooks. My intent was to have this eventually detect if it's running in Azure Automation or not, and support the use of an Azure Automation PSCredential asset.

https://github.com/azureautomation/azure-automation-ise-addon

You can install it using:

```
Install-Module AzureAutomationAuthoringToolkit -Scope CurrentUser -Force
```

**Comment by pcgeek86** [comment]
If this answers your concern, please feel free to close the issue, otherwise I'll come back and close it after a few days. Thanks again @eloekset!

**Comment by eloekset** [comment]
Thanks @pcgeek86! I can confirm that it works without installing the AzureAutomationAuthoringToolkit now, so I'll close this issue.

**Comment by pcgeek86** [comment]
@eloekset Thanks! I'll upload the new module version to the PowerShell Gallery.
