### ISSUE TITLE
Unable to find type [Microsoft.PowerShell.Commands.HttpResponseException].

### ISSUE THREAD

**Issue by ghost** [pcgeek86/PSGitHub#53]
Before submitting your issue for the PSGitHub project, please take a moment to provide the following details:

- [5.1.18362.145] Verison of PowerShell you're using
- [PowerShell Integrated Console] PowerShell host you're using (eg. Console Host, ISE, Visual Studio)
- [Windows 10] Operating system you're running
- [0.15.177] Version of PSGitHub you're using (use `Get-Module -Name PSGitHub`)

I am recieveing the following exception just after installing the module:
`Unable to find type [Microsoft.PowerShell.Commands.HttpResponseException].`

Something to do with [line 95 Invoke-GitHubApi.ps1](https://github.com/pcgeek86/PSGitHub/blob/master/Functions/Private/Invoke-GitHubApi.ps1#L95).

**Comment by felixfbecker** [comment]
I guess that exception type only exists in PowerShell 6+ and the exception type needs to be removed
