### ISSUE TITLE
Problem updating label because required property is missing

### ISSUE THREAD

**Issue by johlju** [pcgeek86/PSGitHub#56]
When updating a label a change at GitHub requires the name to be sent in the request.

```
Invoke-GitHubApi : Validation Failed
See https://developer.github.com/v3/issues/labels/#update-a-label
PATCH https://api.github.com/repos/DscCommunity/DscResource.Analysis/labels/bug UnprocessableEntity
At C:\Users\johlju\Documents\PowerShell\Modules\PSGitHub\0.15.178\Functions\Public\Update-GitHubLabel.ps1:110 char:9
+         Invoke-GitHubApi @apiCall
+         ~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-GitHubApi
```

So this:

https://github.com/pcgeek86/PSGitHub/blob/8a74429264b64a5c90e7a397b8f96f7f0734265f/Functions/Public/Update-GitHubLabel.ps1#L85-L87

Need to change to this:

```powershell
        if ($NewName) {
            $bodyProperties['name'] = $NewName
        } else {
            $bodyProperties['name'] = $Name
        }
```

- [x] Verison of PowerShell you're using: 5.1
- [x] PowerShell host you're using (eg. Console Host, ISE, Visual Studio): Console
- [x] Operating system you're running: Windows 10 Insider 
- [x] Version of PSGitHub you're using (use `Get-Module -Name PSGitHub`): 0.15.178

**Comment by felixfbecker** [comment]
Wanna do a PR?

**Comment by johlju** [comment]
If I have time this weekend I can send in a Pr fixing this.

**Comment by johlju** [comment]
Fix is in PR https://github.com/pcgeek86/PSGitHub/pull/58
