### ISSUE TITLE
Get-GitHubAuthenticatedUser throws

### ISSUE THREAD

**Issue by eloekset** [pcgeek86/PSGitHub#6]
...on Invoke-RestMethod. Cannot send a content-body with this verb-type.
![2016-03-20_11-25-37](https://cloud.githubusercontent.com/assets/791721/13904066/de62a744-ee93-11e5-90fc-1ba9b8251de8.png)

I've found that this is normal behavior of .NET if trying to invoke a GET method with a request body http://stackoverflow.com/a/3981584/1421847. I'll send a PR that checks whether $Body is null or empty before adding it to the `@ApiRequest` hash table.

**Comment by pcgeek86** [comment]
@eloekset Great idea, thank you for finding that and submitting the PR. Merging now.

**Comment by pcgeek86** [comment]
PR has been merged. :)
