### ISSUE TITLE
Add Intellisense auto-completion

### ISSUE THREAD

**Issue by pcgeek86** [pcgeek86/PSGitHub#9]
We need to add Intellisense auto-completion (sometimes called tab-completion) to the PSGitHub PowerShell module. The benefits of Intellisense are significant:
- Reduction in script authoring time
- Minimized need to exit the editor experience
- Improved interactive command line experience
# Priority Work Items
- [x] Auto-completion for GitHub usernames, based on search results
- [x] Auto-completion for GitHub repository names, based on search results
- [x] Auto-completion for issue data (once user has specified owner + repo)
- [x] Auto-completion for Pull Request data (once user has specified owner + repo)

The auto-completer functions and registration should:
1. Be dependent on functionality provided by the PSGitHub module.
2. Have one auto-completer per script file.
3. Be registered upon module import.
4. Use PowerShell Splatting to build the auto-completer data, prior to actual registration by `Register-ArgumentCompleter`.
5. Auto-completers should exist under the `/TabCompleters` folder in this project.

**Comment by felixfbecker** [comment]
I implemented this a while ago :)
